### ISSUE TITLE
We can't use csh because of how we use ssh

### ISSUE THREAD

**Issue by rcthomas** [NERSC/sshspawner#1]
And people who like to use csh complain very loudly about it

**Comment by dmjacobsen** [comment]
What is the problem?  I ran into some similar issues with the mom_remote stuff for salloc.  The issue I had was that interactive sessions, the stdin was apparently frozen (I think that was the issue).

I can dig up my fix if that is helpful and you have a similar problem.

**Comment by shreddd** [comment]
Hi Doug - this is unrelated to SLURM - this is a jupyter issue with how we spawn notebooks. Some hardcoded bash stuff in there.

**Comment by dmjacobsen** [comment]
sure, i get that it's not related to slurm, my discussion was about ssh + csh having issues with forwarding interactive sessions.  Was asking if that is a similar issue.  Sounds like it is not.

**Comment by shreddd** [comment]
@dmjacobsen - ah ok. This particular issue is about assuming bash syntax in our SSH spawner commands which means that things break for CSH users. Examples include the use of bash redirects and exports. 

We did have some issues with frozen stdin which we resolved by adding `< /dev/null` to commands

**Comment by rcthomas** [comment]
Should not be closed.

**Comment by rcthomas** [comment]
Closed by #4
